

name: 'Build and Test'

env:
  GODOT_VERSION: 4.2.1 # Remember to manually set image to this version below.

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write    

    container:
      image: barichello/godot-ci:4.2.1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Move Windows templates into position
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Create staging directory
        run: mkdir -v -p build/windows

      - name: Build
        run: |
          godot -v --export-release --headless "Windows" ../build/windows/game.exe project/project.godot